### ISSUE TITLE
Tradução resposta API

### ISSUE THREAD

**Issue by matheusmacedoap** [wemersonrv/adonis-antl-messages#2]
Olá como consigo traduzir as respostas de requisição via AJAX?

Tenho um app que consume o AdonisJS via Axios como traduzir as  respostas "Invalid user password' ou "Cannot find user with provided email"

**Comment by wemersonrv** [comment]
Faça um interceptor no axios e trate o responde

Em sex, 22 de mai de 2020 10:43, Matheus Macedo <notifications@github.com>
escreveu:
